/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ForgotPaasword: typeof import('./components/ForgotPaasword.vue')['default']
    ForgotPasswordForm: typeof import('./components/ForgotPasswordForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Order: typeof import('./components/Order.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
    UserOrderList: typeof import('./components/UserOrderList.vue')['default']
  }
}
